esphome:
  includes:
    - dsmr_p1_sensor.h
  libraries:
    - "EspSoftwareSerial"
    - "Dsmr"
  name: pulse_meterkast
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_password

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable over-the-air updates
ota:
  password: !secret esphome_ota_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  
uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 115200


sensor:
  - platform: pulse_counter
    pin: GPIO0
    unit_of_measurement: 'liter'
    name: 'Watermeter'

  - platform: custom
    lambda: |-
      auto dsmr_p1_sensor = new DsmrP1CustomSensor(id(uart_bus));
      App.register_component(dsmr_p1_sensor);
      return {dsmr_p1_sensor->s_energy_delivered_tariff1, dsmr_p1_sensor->s_energy_delivered_tariff2, dsmr_p1_sensor->s_energy_returned_tariff1, dsmr_p1_sensor->s_energy_returned_tariff2, dsmr_p1_sensor->s_power_delivered, dsmr_p1_sensor->s_power_returned, dsmr_p1_sensor->instant_power_current_sensor, dsmr_p1_sensor->instant_power_usage_sensor, dsmr_p1_sensor->gas_meter_m3_sensor, dsmr_p1_sensor->actual_tarif_sensor, dsmr_p1_sensor->short_power_outages_sensor, dsmr_p1_sensor->long_power_outages_sensor, dsmr_p1_sensor->short_power_drops_sensor, dsmr_p1_sensor->short_power_peaks_sensor};

    sensors:
    - name: "Consumption Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
    - name: "Consumption High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3  
      filters:
        - multiply: 0.001
    - name: "Return Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
    - name: "Return High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3  
      filters:
        - multiply: 0.001    
    - name: "Actual Consumption Sensor"
      unit_of_measurement: kW
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Actual Delivery Sensor"
      unit_of_measurement: kW
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Instant Power Current Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Instant Power Usage Sensor"
      unit_of_measurement: kW
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Gas Meter M3 Sensor"
      unit_of_measurement: m3
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Actual Tarif Sensor"
    - name: "Short Power Outages Sensor"
      accuracy_decimals: 0      
    - name: "Long Power Outages Sensor"
      accuracy_decimals: 0      
    - name: "Short Power Drops Sensor"
      accuracy_decimals: 0      
    - name: "Short Power Peaks Sensor"
      accuracy_decimals: 0     
